name: "Frank Silvera Writer'sWorshop"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65074
title: "Frank Silvera Writer's Workshop Foundation, Inc."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00caff'
    - '#120d1c'
    - '#cdbdb1'
    - '#ffffff'
    - '#bc4d2a'
  brandStrength: 0.625
  lightness: 0.5299844848923385
  saturation: 0.20404540840536356
  rhythmicContrast: 0.1621117501053959
purpose: []
